<<<<<<< HEAD
definitions:
  models.Category:
    properties:
      description:
        type: string
      id:
        type: integer
=======
basePath: /
definitions:
  models.Category:
    properties:
      id:
        type: integer
      description:
        type: string
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      name:
        type: string
    type: object
  models.Product:
    properties:
<<<<<<< HEAD
      category_id:
        type: integer
      category_name:
        type: string
=======
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
<<<<<<< HEAD
    type: object
  models.ProdukTerlaris:
    properties:
      nama:
        type: string
      qty_terjual:
        type: integer
    type: object
  models.ReportResponse:
    properties:
      produk_terlaris:
        $ref: '#/definitions/models.ProdukTerlaris'
      total_revenue:
        type: integer
      total_transaksi:
        type: integer
    type: object
info:
  contact: {}
=======
      category_id:
        type: integer
      category_name:
        type: string
    type: object
info:
  contact: {}
  description: Dokumentasi API Kasir
  title: Kasir API
  version: "1.0"
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
paths:
  /api/kategori:
    get:
      produces:
<<<<<<< HEAD
      - application/json
=======
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
            items:
<<<<<<< HEAD
              $ref: '#/definitions/models.Category'
            type: array
      summary: List kategori
      tags:
      - Kategori
    post:
      consumes:
      - application/json
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
=======
              $ref: "#/definitions/models.Category"
            type: array
      summary: List kategori
      tags:
        - Kategori
    post:
      consumes:
        - application/json
      parameters:
        - description: payload
          in: body
          name: payload
          required: true
          schema:
            $ref: "#/definitions/models.Category"
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "201":
          description: Created
          schema:
<<<<<<< HEAD
            $ref: '#/definitions/models.Category'
      summary: Buat kategori
      tags:
      - Kategori
  /api/kategori/{id}:
    delete:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
=======
            $ref: "#/definitions/models.Category"
      summary: Buat kategori
      tags:
        - Kategori
  /api/kategori/{id}:
    delete:
      parameters:
        - description: Category ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hapus kategori by ID
      tags:
<<<<<<< HEAD
      - Kategori
    get:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
=======
        - Kategori
    get:
      parameters:
        - description: Category ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
<<<<<<< HEAD
            $ref: '#/definitions/models.Category'
      summary: Detail kategori by ID
      tags:
      - Kategori
    put:
      consumes:
      - application/json
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
=======
            $ref: "#/definitions/models.Category"
      summary: Detail kategori by ID
      tags:
        - Kategori
    put:
      consumes:
        - application/json
      parameters:
        - description: Category ID
          in: path
          name: id
          required: true
          type: integer
        - description: payload
          in: body
          name: payload
          required: true
          schema:
            $ref: "#/definitions/models.Category"
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
<<<<<<< HEAD
            $ref: '#/definitions/models.Category'
      summary: Update kategori by ID
      tags:
      - Kategori
  /api/produk:
    get:
      parameters:
      - description: Filter nama produk (partial match)
        example: Indomie
        in: query
        name: name
        type: string
      produces:
      - application/json
=======
            $ref: "#/definitions/models.Category"
      summary: Update kategori by ID
      tags:
        - Kategori
  /api/produk:
    get:
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
            items:
<<<<<<< HEAD
              $ref: '#/definitions/models.Product'
            type: array
      summary: List produk
      tags:
      - Produk
    post:
      consumes:
      - application/json
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
=======
              $ref: "#/definitions/models.Product"
            type: array
      summary: List produk
      tags:
        - Produk
    post:
      consumes:
        - application/json
      parameters:
        - description: payload
          in: body
          name: payload
          required: true
          schema:
            $ref: "#/definitions/models.Product"
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "201":
          description: Created
          schema:
<<<<<<< HEAD
            $ref: '#/definitions/models.Product'
      summary: Buat produk
      tags:
      - Produk
  /api/produk/{id}:
    delete:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
=======
            $ref: "#/definitions/models.Product"
      summary: Buat produk
      tags:
        - Produk
  /api/produk/{id}:
    delete:
      parameters:
        - description: Product ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hapus produk by ID
      tags:
<<<<<<< HEAD
      - Produk
    get:
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
=======
        - Produk
    get:
      parameters:
        - description: Product ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
<<<<<<< HEAD
            $ref: '#/definitions/models.Product'
      summary: Detail produk by ID
      tags:
      - Produk
    put:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
=======
            $ref: "#/definitions/models.Product"
      summary: Detail produk by ID
      tags:
        - Produk
    put:
      consumes:
        - application/json
      parameters:
        - description: Product ID
          in: path
          name: id
          required: true
          type: integer
        - description: payload
          in: body
          name: payload
          required: true
          schema:
            $ref: "#/definitions/models.Product"
      produces:
        - application/json
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
      responses:
        "200":
          description: OK
          schema:
<<<<<<< HEAD
            $ref: '#/definitions/models.Product'
      summary: Update produk by ID
      tags:
      - Produk
  /api/report:
    get:
      description: start_date dan end_date format YYYY-MM-DD
      parameters:
      - description: Tanggal mulai (YYYY-MM-DD)
        in: query
        name: start_date
        type: string
      - description: Tanggal akhir (YYYY-MM-DD)
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ReportResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Report transaksi berdasarkan rentang tanggal
      tags:
      - Report
  /api/report/hari-ini:
    get:
      description: Mengambil total revenue, total transaksi, dan produk terlaris untuk
        hari ini (Asia/Jakarta)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ReportResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Report transaksi hari ini
      tags:
      - Report
=======
            $ref: "#/definitions/models.Product"
      summary: Update produk by ID
      tags:
        - Produk
>>>>>>> d341803c019bcc13dfc7d5f90c14a62876d7e0da
swagger: "2.0"
